### ISSUE TITLE
Compiling warning

### ISSUE THREAD

**Issue by barkovv** [hanschen/Procrastinate-No-More#1]
If compiling on OS with Qt5 I get error " QT_QT_UNCLUDE_DIR is unset " from cmake.
Problem can be solved by using "cmake -DCMAKE_INSTALL_PREFIX=`kde4-config --prefix` -DQT_QMAKE_EXECUTABLE=/usr/bin/qmake-qt4 .. " command. Adding this info could be useful for somebody.

**Comment by hanschen** [comment]
Thanks for the tip, I've added this information to the README.
